apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ananas-pvc
  namespace: jenkins
  labels:
    app: jenkins-pod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
