apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
 type: LoadBalancer
 ports:
   - name: jenkins
     port: 80
     targetPort: 8080
     nodePort: 31111
 selector:
   name: jenkins    
